#!/bin/sh
if test ! -f $1 
then
cat <<!  > $1
package main

import (
  svglib "./svg"
  "os"
)

var (
  width = 500
  height = 500
  svg = svglib.New(os.Stdout)
)

func background(v int) { svg.Rect(0, 0, width, height, svg.RGB(v, v, v)) }


func main() {
  svg.Start(width, height)
  background(255)
  
  // your code here
  
  svg.Grid(0, 0, width, height, 10, "stroke:black;opacity:0.1")
  svg.End()
}
!
fi
$EDITOR $1
