#!/bin/sh
cat <<!  > $*
package main

import (
  "./svg"
)

var width = 500
var height = 500


func main() {

  svg.Start(width, height)
  
  svg.Grid(0, 0, width, height, 10, "stroke:black;opacity:0.1")
  svg.End()

}

!
edit $*