#!/bin/sh
#
# Compile the library and clients, run the clients, display the results
#
#
list="svgdef flower funnel imfade lewitt planets randcomp richter rl vismem android svgopher"

case $GOARCH in
  arm)    A=5;;
  amd64)  A=6;;
  386)    A=8;;
  *)      exit;;
esac

case $GOOS in
  darwin)   opener="open -a /Applications/Safari.app";; 
  linux)    opener="firefox";;
  freebsd)  opener="firefox";;
  *) exit;;
esac
  

${A}g svg.go && 
for i in $list
do
  rm -f $i.svg ./$i
  ${A}g $i.go && ${A}l -o $i $i.${A} && ./$i > $i.svg
  $opener $i.svg
  rm $i.${A}
done
